# Generated by Django 5.2.17 on 2026-08-31 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=180, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='catalog/brands/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='Mise en avant')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='Titre SEO')),
                ('seo_description', models.CharField(blank=True, max_length=170, verbose_name='Description SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='brand_active_order_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Nom')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=180, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/categories/', verbose_name='Image')),
                ('icon', models.CharField(blank=True, help_text="Nom ou classe d'icône utilisée par l'interface.", max_length=100, verbose_name='Icône')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_featured_home', models.BooleanField(db_index=True, default=False, verbose_name='Mise en avant accueil')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='Titre SEO')),
                ('seo_description', models.CharField(blank=True, max_length=170, verbose_name='Description SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='catalog.category', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='cat_active_order_idx'), models.Index(fields=['parent', 'is_active'], name='cat_parent_active_idx')],
            },
        ),
    ]
