# Generated by Django 5.2.17 on 2026-08-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="Nom ou classe de l'icône utilisée par l'interface.", max_length=100, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True, verbose_name='Slug'),
        ),
    ]
