# Generated by Django 5.2.17 on 2026-08-31 09:29

import catalog.image_utils
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_brand_slug_alter_category_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('data_type', models.CharField(choices=[('TEXT', 'Texte'), ('NUMBER', 'Nombre'), ('COLOR', 'Couleur'), ('BOOLEAN', 'Oui / Non')], default='TEXT', max_length=20, verbose_name='Type')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Attribut',
                'verbose_name_plural': 'Attributs',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=100, verbose_name='Icône'),
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150, verbose_name='Valeur')),
                ('display_value', models.CharField(blank=True, max_length=150, verbose_name='Valeur affichée')),
                ('color_hex', models.CharField(blank=True, help_text='#000000', max_length=9, verbose_name='Couleur HEX')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.attribute', verbose_name='Attribut')),
            ],
            options={
                'verbose_name': "Valeur d'attribut",
                'verbose_name_plural': "Valeurs d'attributs",
                'ordering': ['attribute__display_order', 'display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=220, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Code-barres')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Description courte')),
                ('description', models.TextField(blank=True, verbose_name='Description complète')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix de vente')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name="Prix d'achat")),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('ARCHIVED', 'Archivé')], db_index=True, default='DRAFT', max_length=20, verbose_name='Statut')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='Mis en avant')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='Titre SEO')),
                ('seo_description', models.CharField(blank=True, max_length=170, verbose_name='Description SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='Marque')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, verbose_name='Obligatoire')),
                ('is_variant_axis', models.BooleanField(default=True, verbose_name='Utilisé pour les variantes')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_attributes', to='catalog.attribute', verbose_name='Attribut')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='catalog.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Attribut produit',
                'verbose_name_plural': 'Attributs produits',
                'ordering': ['display_order', 'attribute__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/products/', validators=[catalog.image_utils.validate_catalog_image], verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Texte alternatif')),
                ('is_primary', models.BooleanField(db_index=True, default=False, verbose_name='Image principale')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Image produit',
                'verbose_name_plural': 'Images produits',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='SKU variante')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Code-barres')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Laisser vide pour utiliser le prix du produit.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix spécifique')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/variants/', validators=[catalog.image_utils.validate_catalog_image], verbose_name='Image')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
                'ordering': ['product__name', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='VariantAttributeSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_selections', to='catalog.attributevalue', verbose_name='Valeur')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='catalog.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': "Sélection d'attribut variante",
                'verbose_name_plural': "Sélections d'attributs variantes",
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, related_name='variants', through='catalog.VariantAttributeSelection', to='catalog.attributevalue'),
        ),
        migrations.AddConstraint(
            model_name='attributevalue',
            constraint=models.UniqueConstraint(fields=('attribute', 'value'), name='unique_attribute_value'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'category'], name='product_status_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'status'], name='product_brand_status_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'status'], name='product_featured_idx'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.UniqueConstraint(fields=('product', 'attribute'), name='unique_product_attribute'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='unique_primary_product_image'),
        ),
        migrations.AddConstraint(
            model_name='variantattributeselection',
            constraint=models.UniqueConstraint(fields=('variant', 'attribute_value'), name='unique_variant_attribute_value'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='variant_product_active_idx'),
        ),
    ]
