# Generated by Django 5.2.17 on 2026-09-15 15:49

import catalog.image_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_attribute_alter_category_icon_attributevalue_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='catalog/brands/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='catalog/categories/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='catalog/products/', validators=[catalog.image_utils.validate_catalog_image], verbose_name='Image'),
        ),
    ]
