# Generated by Django 5.2.17 on 2026-08-31 14:14

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_attribute_alter_category_icon_attributevalue_product_and_more'),
        ('checkout', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Numéro de commande')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('PREPARING', 'En préparation'), ('READY', 'Prête'), ('SHIPPED', 'Expédiée'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], db_index=True, default='PENDING', max_length=20, verbose_name='Statut')),
                ('customer_name', models.CharField(max_length=180, verbose_name='Nom du client')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('customer_whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('delivery_method', models.CharField(choices=[('DELIVERY', 'Livraison'), ('PICKUP', 'Retrait')], max_length=20, verbose_name='Mode de réception')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Ville')),
                ('delivery_zone', models.CharField(blank=True, max_length=180, verbose_name='Quartier / zone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('notes', models.TextField(blank=True, verbose_name='Instructions client')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sous-total')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Livraison')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('checkout_session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='checkout.checkoutsession', verbose_name='Session checkout')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Produit snapshot')),
                ('sku', models.CharField(max_length=120, verbose_name='SKU snapshot')),
                ('variant_label', models.CharField(blank=True, max_length=500, verbose_name='Variante snapshot')),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix normal')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix vendu')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total ligne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inventory.inventoryitem', verbose_name='Stock')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='Produit')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Article commande',
                'verbose_name_plural': 'Articles commandes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Référence paiement')),
                ('method', models.CharField(choices=[('CASH_ON_DELIVERY', 'Paiement à la livraison'), ('PAY_AT_PICKUP', 'Paiement au retrait')], max_length=30, verbose_name='Mode de paiement')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé'), ('REFUNDED', 'Remboursé')], db_index=True, default='PENDING', max_length=20, verbose_name='Statut')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant')),
                ('currency', models.CharField(default='XOF', max_length=10, verbose_name='Devise')),
                ('provider', models.CharField(blank=True, max_length=80, verbose_name='Prestataire')),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Référence prestataire')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ID transaction')),
                ('provider_payload', models.JSONField(blank=True, default=dict, verbose_name='Données prestataire')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='Commande')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='order_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='order_subtotal_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_fee__gte', 0)), name='order_delivery_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='order_total_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_item_qty_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payment_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_gte_zero'),
        ),
    ]
