# Generated by Django 5.2.17 on 2026-08-31 13:26

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_attribute_alter_category_icon_attributevalue_product_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expirée'), ('CANCELLED', 'Annulée'), ('CONVERTED', 'Convertie en commande')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('customer_name', models.CharField(max_length=180, verbose_name='Nom du client')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('customer_whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('delivery_method', models.CharField(choices=[('DELIVERY', 'Livraison'), ('PICKUP', 'Retrait')], default='DELIVERY', max_length=20, verbose_name='Mode de livraison')),
                ('city', models.CharField(default='Bamako', max_length=120, verbose_name='Ville')),
                ('delivery_zone', models.CharField(blank=True, max_length=180, verbose_name='Zone / quartier')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('notes', models.TextField(blank=True, verbose_name='Instructions')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sous-total')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Frais de livraison')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expire le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
            ],
            options={
                'verbose_name': 'Session checkout',
                'verbose_name_plural': 'Sessions checkout',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='checkout_status_exp_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='checkout_subtotal_gte_zero'), models.CheckConstraint(condition=models.Q(('delivery_fee__gte', 0)), name='checkout_delivery_gte_zero'), models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='checkout_total_gte_zero')],
            },
        ),
        migrations.CreateModel(
            name='CheckoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Nom snapshot')),
                ('sku', models.CharField(max_length=120, verbose_name='SKU snapshot')),
                ('variant_label', models.CharField(blank=True, max_length=500, verbose_name='Variante snapshot')),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix normal')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix appliqué')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total ligne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_items', to='inventory.inventoryitem', verbose_name='Stock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_items', to='catalog.product', verbose_name='Produit')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkout_items', to='catalog.productvariant', verbose_name='Variante')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.checkoutsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Article checkout',
                'verbose_name_plural': 'Articles checkout',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['session', 'product'], name='checkout_item_session_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='checkout_item_qty_gt_zero')],
            },
        ),
    ]
