# Generated by Django 5.2.17 on 2026-08-31 09:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import promotions.image_utils
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_attribute_alter_category_icon_attributevalue_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='Nom')),
                ('logo', models.ImageField(upload_to='partners/logos/', validators=[promotions.image_utils.validate_ad_image], verbose_name='Logo')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('page_url', models.CharField(blank=True, max_length=500, verbose_name='Lien interne')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=230, unique=True, verbose_name='Slug')),
                ('campaign_type', models.CharField(choices=[('STANDARD', 'Promotion'), ('SALE', 'Soldes')], db_index=True, default='STANDARD', max_length=20, verbose_name='Type de campagne')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Pourcentage'), ('FIXED_AMOUNT', 'Montant fixe'), ('FIXED_PRICE', 'Prix promotionnel fixe')], max_length=20, verbose_name='Type de réduction')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valeur de la réduction')),
                ('target_mode', models.CharField(choices=[('ALL', 'Tous les produits'), ('CATEGORY', 'Une catégorie'), ('BRAND', 'Une marque'), ('PRODUCTS', 'Produits sélectionnés')], db_index=True, max_length=20, verbose_name='Cible')),
                ('badge_text', models.CharField(blank=True, default='🔥 PROMO', max_length=60, verbose_name='Badge')),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='Début')),
                ('end_at', models.DateTimeField(db_index=True, verbose_name='Fin')),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Priorité')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='catalog.product', verbose_name='Produits concernés')),
                ('target_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='catalog.brand', verbose_name='Marque ciblée')),
                ('target_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='catalog.category', verbose_name='Catégorie ciblée')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-priority', '-start_at'],
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=180, verbose_name='Entreprise')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='advertising/logos/', validators=[promotions.image_utils.validate_ad_image], verbose_name='Logo entreprise')),
                ('title', models.CharField(max_length=220, verbose_name='Titre')),
                ('text', models.CharField(blank=True, max_length=500, verbose_name='Petit texte')),
                ('desktop_image', models.ImageField(upload_to='advertising/desktop/', validators=[promotions.image_utils.validate_ad_image], verbose_name='Image desktop')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='advertising/mobile/', validators=[promotions.image_utils.validate_ad_image], verbose_name='Image mobile')),
                ('button_text', models.CharField(blank=True, default="Voir l'offre", max_length=80, verbose_name='Texte bouton')),
                ('button_url', models.CharField(blank=True, max_length=500, verbose_name='Lien personnalisé')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('placement', models.CharField(choices=[('HOME_HERO', 'A — Grande bannière accueil'), ('HOME_MIDDLE', 'B — Entre catégories et produits'), ('CATEGORY', 'C — Page catégorie'), ('PRODUCT', 'D — Page détail produit'), ('CART', 'E — Panier'), ('MOBILE_BANNER', 'F — Petite bannière mobile')], db_index=True, max_length=30, verbose_name='Emplacement')),
                ('priority_level', models.PositiveSmallIntegerField(choices=[(10, 'Normale'), (20, 'Importante'), (30, 'Premium')], db_index=True, default=10, verbose_name='Niveau de priorité')),
                ('display_priority', models.PositiveIntegerField(db_index=True, default=0, verbose_name="Priorité d'affichage")),
                ('display_old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ancien prix affiché')),
                ('display_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix affiché')),
                ('destination_type', models.CharField(choices=[('PRODUCT', 'Produit'), ('CATEGORY', 'Catégorie'), ('BRAND', 'Marque'), ('PAGE', 'Page spéciale'), ('WHATSAPP', 'WhatsApp'), ('WEBSITE', 'Site partenaire'), ('CUSTOM', 'Lien personnalisé')], default='CUSTOM', max_length=20, verbose_name='Type de destination')),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='Début')),
                ('end_at', models.DateTimeField(db_index=True, verbose_name='Fin')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('hide_after_expiry', models.BooleanField(default=True, verbose_name='Masquer après expiration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('destination_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_advertisements', to='catalog.brand', verbose_name='Marque destination')),
                ('destination_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_advertisements', to='catalog.category', verbose_name='Catégorie destination')),
                ('destination_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_advertisements', to='catalog.product', verbose_name='Produit destination')),
                ('target_categories', models.ManyToManyField(blank=True, related_name='targeted_advertisements', to='catalog.category', verbose_name='Catégories contextuelles')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to='promotions.promotion', verbose_name='Promotion associée')),
            ],
            options={
                'verbose_name': 'Publicité',
                'verbose_name_plural': 'Publicités',
                'ordering': ['-priority_level', '-display_priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Date')),
                ('impressions', models.PositiveBigIntegerField(default=0, verbose_name='Impressions')),
                ('clicks', models.PositiveBigIntegerField(default=0, verbose_name='Clics')),
                ('orders_count', models.PositiveBigIntegerField(default=0, verbose_name='Commandes')),
                ('attributed_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name="Chiffre d'affaires attribué")),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='promotions.advertisement', verbose_name='Publicité')),
            ],
            options={
                'verbose_name': 'Statistique publicitaire',
                'verbose_name_plural': 'Statistiques publicitaires',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('advertisement', 'date'), name='unique_ad_daily_stat')],
            },
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active', 'start_at', 'end_at'], name='promo_active_period_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['campaign_type', 'is_active'], name='promo_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['target_mode', 'is_active'], name='promo_target_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='promo_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['placement', 'is_active', 'start_at', 'end_at'], name='ad_place_period_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['priority_level', 'display_priority'], name='ad_priority_idx'),
        ),
        migrations.AddConstraint(
            model_name='advertisement',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='ad_end_after_start'),
        ),
    ]
