# Generated by Django 5.2.17 on 2026-08-31 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_attribute_alter_category_icon_attributevalue_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.PositiveIntegerField(default=0, verbose_name='Stock physique')),
                ('quantity_reserved', models.PositiveIntegerField(default=0, verbose_name='Stock réservé')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, verbose_name="Seuil d'alerte")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modifié le')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='catalog.product', verbose_name='Produit')),
                ('variant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='catalog.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['product__name', 'variant__sku'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RECEIVE', 'Entrée'), ('REMOVE', 'Sortie'), ('RESERVE', 'Réservation'), ('RELEASE', 'Libération réservation'), ('SALE', 'Vente'), ('RETURN', 'Retour'), ('ADJUSTMENT', 'Ajustement')], db_index=True, max_length=20, verbose_name='Type')),
                ('quantity_delta', models.IntegerField(default=0, verbose_name='Variation stock physique')),
                ('reserved_delta', models.IntegerField(default=0, verbose_name='Variation stock réservé')),
                ('quantity_after', models.PositiveIntegerField(verbose_name='Stock physique après')),
                ('reserved_after', models.PositiveIntegerField(verbose_name='Stock réservé après')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Référence')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventoryitem', verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['product', 'updated_at'], name='inventory_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('product',), name='unique_base_inventory_item'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', 0)), name='inventory_on_hand_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_reserved__gte', 0)), name='inventory_reserved_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_reserved__lte', models.F('quantity_on_hand'))), name='inventory_reserved_lte_on_hand'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['inventory_item', 'created_at'], name='stock_move_item_date_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='stock_move_type_date_idx'),
        ),
    ]
